"""followers

Revision ID: 01435ae1ed0b
Revises: 4615fcb11fe1
Create Date: 2020-11-28 21:06:45.333565

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "01435ae1ed0b"
down_revision = "4615fcb11fe1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["followed_id"], ["user.id"]),
        sa.ForeignKeyConstraint(["follower_id"], ["user.id"]),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers")
    # ### end Alembic commands ###
