"""new fields in user model

Revision ID: 4615fcb11fe1
Revises: 71b88e954706
Create Date: 2020-11-26 20:20:20.073523

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4615fcb11fe1"
down_revision = "71b88e954706"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("about_me", sa.String(length=140), nullable=True),
    )
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    op.drop_column("user", "about_me")
    # ### end Alembic commands ###
